version: '2'

services:
  pihole:
    extends:
      service: pihole
      file: dns/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.123.201

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.123.0/24
          gateway: 192.168.123.1
          ip_range: 192.168.123/28
